---
- name: Include vars
  include_vars: ../vars/ah_ee_repositories.yml
  tags:
    - alltags
    - repos

- import_role:
    name: redhat_cop.ah_configuration.ee_repository
  tags:
    - alltags
    - repos
...
