---
- name: Include vars
  include_vars: ../vars/ah_collection_namespaces.yml
  tags:
    - alltags
    - namespaces

- import_role:
    name: redhat_cop.ah_configuration.namespace
  tags:
    - alltags
    - namespaces
...
