---
- name: Include vars
  include_vars: ../vars/ah_ee_repository_sync.yml
  tags:
    - alltags
    - reposync

- import_role:
    name: redhat_cop.ah_configuration.ee_repository_sync
  tags:
    - alltags
    - reposync
...
