---
- name: Include vars
  include_vars: ../vars/ah_ee_registry_indices.yml
  tags:
    - alltags
    - indices

- import_role:
    name: redhat_cop.ah_configuration.ee_registry_index
  tags:
    - alltags
    - indices
...
