---
- name: Include vars
  include_vars: ../vars/ah_users
  tags:
    - alltags
    - users

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.user
  tags:
    - alltags
    - users
...
