---
- name: Include vars
  include_vars: ../vars/ah_ee_registries.yml
  tags:
    - alltags
    - registries

- import_role:
    name: redhat_cop.ah_configuration.ee_registry
  tags:
    - alltags
    - registries
...
